roles:
  - name: geerlingguy.docker
    version: 7.0.1
collections:
  - name: https://github.com/kencx/ansible-collection.git
    type: git
    version: v0.4.0  # Pinned to stable version (2023-11-04)
  - name: community.docker
